### ISSUE TITLE
Knife round ready hint at the start of every Round

### ISSUE THREAD

**Issue by Siiggyy** [dejavueakay/orangebot#1]
"Knife round will start when both teams are !ready" appears at the start of every round, more or less at 7 seconds in the freezetime and mid round.

**Comment by dejavueakay** [comment]
Hey Cyrill, the next time this message appears can you write !debug and paste the output here? Would appreciate :)

Also, what OS / architecture and did you use a binary or the script itself? if you used the script, which version did you use?

**Comment by dejavueakay** [comment]
Is it possible that you started two bots at the same time? also, we need your config.json (remove your rcon and mask the ip obviously) and any info you can provide to understand what is going on

**Comment by Siiggyy** [comment]
Thanks for your fast reply.
I use Ubuntu 16.04.4 LTS
I downloadet it over git.
Thats the output i get from !debug
Console: live: false paused: false freeze: false knife: true knifewinner: false ready: T:false CT:false unpause: T:false CT:false
Console: mix1 [] mix2
I started the bot over the command line because my autostart didnt worked.
[config.txt](https://github.com/dejavueakay/orangebot/files/1861699/config.txt)

**Comment by dejavueakay** [comment]
hey cyrill, nothing to thank me for! did you try to !start a match? what does it do if you type !start?

**Comment by Siiggyy** [comment]
It starts the map normally everthing works fine just the message appears every time.

**Comment by dejavueakay** [comment]
Would you have some minutes to have a closer look at this problem? I'd really appreciate your time! If so, add me on steam: http://steamcommunity.com/id/parisienne

Or, you could try a fix a user found in a similar problem:

Go to the cfg folder and add to the very end of warmup.cfg the following two lines:
```
log off
log on
```
and try again.

**Comment by Siiggyy** [comment]
Just added you on Steam.

**Comment by dejavueakay** [comment]
Resolved issue: Bot was running on the same LAN as the CSGO Server and serverType was not set to local. The server was once added by the config.json and once "on-the-fly" due to an old logaddress entry on the server. If you run into a similar problem (bot giving out everything double), check your config.json and try to do a "rcon logaddress_delall" and restart the bot.
